### ISSUE TITLE
How to run an existing jar job

### ISSUE THREAD

**Issue by ashitabh** [level11data/databricks-client-java#1]
How can I run/rerun an existing jar job ( suppose the Job id is 100) ?

**Comment by pohlposition** [comment]
You could use the method getJob(long jobID) on the DatabrickSession to return a Job.  Then just call run() on the Job.

**Comment by ashitabh** [comment]
Please let me know how to pass new arguments to the job. I am getting error when trying .run with argument.
            long jobId = 52;
            Job myJob = _databricks.getJob(jobId);
            
            List<String> baseParams = new ArrayList<String>();
            baseParams.add("hello");
            baseParams.add("world");

            JobRun run = myJob.run(baseParams);   // getting error run() in job can't be applied to Java.util.List<Java.lang.String>

**Comment by ashitabh** [comment]
thanks :)
