### ISSUE TITLE
Accepting contributions?

### ISSUE THREAD

**Issue by sandeepraju** [level11data/databricks-client-java#3]
I'd like to add some documentation, examples, maven central coordinates, etc.
@pohlposition are you accepting contributions?

**Comment by pohlposition** [comment]
@sandeepraju , I'd be open to contributions :)

This has been a side project of mine that I try to develop as I have time, so progress has been sporadic.

I haven't actually ever cut a release, so it's not on maven yet.  I think there is sufficient functionality now to do so.  

I think the next thing for me to do is to:
1. Add some documentation, starting with a README
2. Include a release process and start publishing to maven central

**Comment by pohlposition** [comment]
If you have experience with leveraging jersey for secure https sessions, I'd love some feedback on this part.  It's not something I've done too much of in java, and I want to make sure it passes muster:

https://github.com/level11data/databricks-client-java/blob/master/src/main/java/com/level11data/databricks/client/DatabricksSession.java#L73

**Comment by sandeepraju** [comment]
Sorry, looks like this slipped through the cracks. I haven't had much experience with Jersey but looks fine on an overview!
